analytics: {}
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.5
  lightness: 0.724662
  rhythmicContrast: 0.488175
  saturation: 0.474662
cta: {}
layout_spectrum: 0.317567
name: Vubly
opengraph: {}
purpose: []
typography_spectrum: 0.88063
